### ISSUE TITLE
Null error on Intent action

### ISSUE THREAD

**Issue by ibrahim-mubarak** [daadu/receive_intent#10]
We are seeing the following reports on our Error Reporter

> _TypeError: type 'Null' is not a subtype of type 'String'
>   File "receive_intent.dart", line 37, in new Intent.fromMap
>   File "receive_intent.dart", line 75, in ReceiveIntent.getInitialIntent
> 

Which seems to be while getting the action for Intent, not sure when this is actually null however.

**Comment by daadu** [comment]
You might be on an older version, #9 fixes allowing "null" action. Can you run `flutter pub upgrade` and see if it is fixed.

**Comment by ibrahim-mubarak** [comment]
You're right,
Thanks for pointing that out
