### ISSUE TITLE
await ReceiveIntent.setResult Not working

### ISSUE THREAD

**Issue by sikandernoori** [daadu/receive_intent#2]
Hello @daadu 

I am performing Intent using below Code which works fine.

```
onPressed: () => android_intent.Intent()
                   ..setAction("com.packagename.MYINTENT")
                  ..startActivityForResult().then(
                    (data) {
                      print("mydata " + data.toString());
                      setState(() {
                        _scanBarcode = data.toString();
                      });
                    },
                    onError: (e) => print("error occured: " + e.toString()),
                  ),
```

The intent Open the App and after performing the Functionality I am calling your Plugin like below:

```
Future<void> _setActivityResult() async {
    await ReceiveIntent.setResult(999, data: {"sum": 123}, shouldFinish: true);
  }
```

After this function App Closes and I am back to parent App from where I Launched the Activity but in result the data is not being showed.
Am i missing any additional parameter ?

**Comment by daadu** [comment]
Can you confirm that the "data" in the code is what you are calling it with.

There are restriction to what "type" of data could be send, It has to be one of the following -> `String`, `int`, `bool`, `double` or another `Map`.

Check this function to know more - https://github.com/daadu/receive_intent/blob/46d650265d14da31d65ad97009f1d77eeb1c47f8/android/src/main/kotlin/com/bhikadia/receive_intent/ReceiveIntentPlugin.kt#L37

**Comment by sikandernoori** [comment]
I think maybe your Plugin is working Okay.

**Comment by daadu** [comment]
Which plugin are you using to call the "AcitivtyForResult" ?

**Comment by daadu** [comment]
`receive_intent` puts the data in "Intent.bundle", maybe that plugin maybe expecting something else in callback?

**Comment by sikandernoori** [comment]
> Which plugin are you using to call the "AcitivtyForResult" ?

https://pub.dev/packages/intent

**Comment by daadu** [comment]
The code (of `intent` plugin) indicates, that it is looking for "Intent.data" with some specific type - filepath, URL, etc.

Check following:
https://github.com/itzmeanjan/intent/blob/7ebae1dac32058dcefa622f52ee4da354146769a/android/src/main/kotlin/io/github/itzmeanjan/intent/IntentPlugin.kt#L39-L78

While our plugin puts the data in `Intent.bundle`, that is why you are not getting the data in the callback.

**Comment by sikandernoori** [comment]
Can you Suggest an alternative to get this working ?

**Comment by daadu** [comment]
Opened a new issue regarding it #3. Feel free to file PR for it.

**Comment by daadu** [comment]
As of now you can wait or code #3 your self.

OR

Use [`linker`](https://pub.dev/packages/linker) plugin, I haven't used myself, but quick look at their code - suggests that in callback you will get "full intent", you should find the "data" in that "result"

**Comment by daadu** [comment]
Also, I am incorrect above, we put "data" in `Intent.extras`

**Comment by sikandernoori** [comment]
Thank You @daadu.

It seems like the best forward is to write my own plugin for `StartActivityForResult` after that maybe I can use your Plugin `Intent` for closing Activity.
