### ISSUE TITLE
receivedIntentStream doesnt work properly with xml files

### ISSUE THREAD

**Issue by worldwidee** [daadu/receive_intent#22]
Hello, thanks for the package. 
I need to receive shared xml files by listening but it returns null data and it returns a meaningless uri. This is what i receive when i print intent

`Intent(fromPackageName: null, fromSignatures: null, action: android.intent.action.SEND, data: null, categories: [android.intent.category.DEFAULT], extra: {android.intent.extra.STREAM: content://com.android.providers.downloads.documents/document/57})`

my code snip:

```dart
    _intentDataStreamSubscription =
        ReceiveIntent.receivedIntentStream.listen((Intent? intent) async {
      if (intent?.extra != null) {
        print(intent!);
      }
    }, onError: (err) {
      // Handle exception
    });
```

**Comment by daadu** [comment]
It is content URI - exactly what you are looking for to access the file.

Use one of the following to get file data:
- https://pub.dev/packages/uri_to_file
- https://pub.dev/packages/uri_content

**Comment by daadu** [comment]
Closing this, feel free to ask to reopen if issue is unresolved.
